name: Generate Transcript

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the YouTube video'
        required: true
        type: string
      language:
        description: 'Language code for translation (e.g., en, es, fr)'
        required: true
        type: string

jobs:
  generate-transcript:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp openai-whisper googletrans==4.0.0-rc1

    - name: Download and transcribe audio
      run: |
        python generate_transcript.py "${{ github.event.inputs.url }}" "${{ github.event.inputs.language }}"

    - name: Upload transcript
      uses: actions/upload-artifact@v3
      with:
        name: transcript
        path: transcript.txt
