name: Generate Transcript

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the video'
        required: true
        type: string
      language:
        description: 'Language for translation (optional)'
        required: false
        type: string
        default: 'en'

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install whisper googletrans==4.0.0-rc1
          sudo apt-get install -y ffmpeg

      - name: Download video
        run: |
          ffmpeg -i ${{ github.event.inputs.url }} -c copy video.mp4

      - name: Transcribe audio
        run: |
          python transcribe.py

      - name: Translate transcript
        if: ${{ github.event.inputs.language != 'en' }}
        run: |
          python translate.py ${{ github.event.inputs.language }}

      - name: Upload transcript
        uses: actions/upload-artifact@v3
        with:
          name: transcript
          path: ${{ github.event.inputs.language != 'en' && 'transcript_translated.txt' || 'transcript.txt' }}
