name: Video Transcript

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the video'
        required: true
        type: string

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          sudo apt-get install -y ffmpeg

      - name: Download and transcribe video
        run: node download_and_transcribe.js ${{ github.event.inputs.url }}

      - name: Upload transcript
        uses: actions/upload-artifact@v3
        with:
          name: transcript
          path: transcript.txt
